// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './createdatequestions.css';

function render() {
    return <div className="createdatequestions-createdatequestions-7">
        <div className="createdatequestions-0">
            <div className="createdatequestions-path-5">
                <div className="createdatequestions-0-0-0">
                    <div className="createdatequestions-0-0-0-0">
                        <div className="createdatequestions-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1233826191090713-1523741622317-B22F1F13-8F1B-4419-9E4F-04569DD17358.png" className="createdatequestions-arrow-left-1" /> 
                        </div>
                    </div>
                    <div className="createdatequestions-0-0-0-1">
                        <div className="createdatequestions-0-0-0-1-0">
                            <div className="createdatequestions-title-9">
                                {"Don’t Forget"}
                            </div>
                        </div>
                    </div>
                    <div className="createdatequestions-0-0-0-2">
                        <div className="createdatequestions-0-0-0-2-0">
                            <div className="createdatequestions-title_copy-5">
                                Save
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="createdatequestions-1">
            <div className="createdatequestions-title-1">
                {"Things to remember…"}
            </div>
        </div>
        <div className="createdatequestions-2">
            <div className="createdatequestions-2-0">
                <div className="createdatequestions-2-0-0">
                    <div className="createdatequestions-check_box-7">
                        <input type="checkbox" className="createdatequestions-2-0-0-0-0" /> 
                    </div>
                </div>
            </div>
            <div className="createdatequestions-the_first_thing_that-1">
                {"The first thing that you shouldn’t forget"}
            </div>
        </div>
        <div className="createdatequestions-3">
            <div className="createdatequestions-3-0">
                <div className="createdatequestions-3-0-0">
                    <div className="createdatequestions-check_box-5">
                        <input type="checkbox" className="createdatequestions-3-0-0-0-0" /> 
                    </div>
                </div>
            </div>
            <div className="createdatequestions-the_second_thing_tha-9">
                {"The second thing that you shouldn’t forget"}
            </div>
        </div>
        <div className="createdatequestions-4">
            <div className="createdatequestions-4-0">
                <div className="createdatequestions-4-0-0">
                    <div className="createdatequestions-check_box-77">
                        <input type="checkbox" className="createdatequestions-4-0-0-0-0" /> 
                    </div>
                </div>
            </div>
            <div className="createdatequestions-the_third_thing_that-1">
                {"The third thing that you shouldn’t forget"}
            </div>
        </div>
        <div className="createdatequestions-5" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}