// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './create_date_copy_4.css';

function render() {
    return <div className="create_date_copy_4-create_date_copy_4">
        <div className="create_date_copy_4-0">
            <div className="create_date_copy_4-path-1">
                <div className="create_date_copy_4-0-0-0">
                    <div className="create_date_copy_4-0-0-0-0">
                        <div className="create_date_copy_4-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7557523562490795-1523741622119-287566B8-BA66-4FEF-9EAB-54D55985EF6E.png" className="create_date_copy_4-arrow-left-7" /> 
                        </div>
                    </div>
                    <div className="create_date_copy_4-title-1">
                        Shared Debrief
                    </div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_4-1">
            <div className="create_date_copy_4-title-10">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="create_date_copy_4-2">
            <div className="create_date_copy_4-2-0">
                <div className="create_date_copy_4-2-0-0">
                    <div className="create_date_copy_4-path-12" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_first_option_to-1">
                The first option to the first question 
            </div>
        </div>
        <div className="create_date_copy_4-3">
            <div className="create_date_copy_4-3-0">
                <div className="create_date_copy_4-3-0-0">
                    <div className="create_date_copy_4-path-3" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_second_option_to-6">
                The second option to the first question
            </div>
        </div>
        <div className="create_date_copy_4-4">
            <div className="create_date_copy_4-4-0">
                <div className="create_date_copy_4-4-0-0">
                    <div className="create_date_copy_4-path-14" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_third_otion_to_t-1">
                The third otion to the first question is this
            </div>
        </div>
        <div className="create_date_copy_4-5">
            <div className="create_date_copy_4-path-6">
                <div className="create_date_copy_4-5-0-0">
                    <div className="create_date_copy_4-anything_you_want_to-1">
                        {"Anything you want to add?"}
                    </div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_4-6">
            <div className="create_date_copy_4-title-11">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="create_date_copy_4-7">
            <div className="create_date_copy_4-7-0">
                <div className="create_date_copy_4-7-0-0">
                    <div className="create_date_copy_4-path-4" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_first_option_to-5">
                The first option to the first question 
            </div>
        </div>
        <div className="create_date_copy_4-8">
            <div className="create_date_copy_4-8-0">
                <div className="create_date_copy_4-8-0-0">
                    <div className="create_date_copy_4-path-15" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_second_option_to-68">
                The second option to the first question
            </div>
        </div>
        <div className="create_date_copy_4-9">
            <div className="create_date_copy_4-9-0">
                <div className="create_date_copy_4-9-0-0">
                    <div className="create_date_copy_4-path-2" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_third_otion_to_t-4">
                The third otion to the first question is this
            </div>
        </div>
        <div className="create_date_copy_4-10">
            <div className="create_date_copy_4-title-4">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="create_date_copy_4-11">
            <div className="create_date_copy_4-11-0">
                <div className="create_date_copy_4-11-0-0">
                    <div className="create_date_copy_4-path-17" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_first_option_to-8">
                The first option to the first question 
            </div>
        </div>
        <div className="create_date_copy_4-12">
            <div className="create_date_copy_4-12-0">
                <div className="create_date_copy_4-12-0-0">
                    <div className="create_date_copy_4-path-172" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_second_option_to-1">
                The second option to the first question
            </div>
        </div>
        <div className="create_date_copy_4-13">
            <div className="create_date_copy_4-13-0">
                <div className="create_date_copy_4-13-0-0">
                    <div className="create_date_copy_4-path-142" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_third_otion_to_t-9">
                The third otion to the first question is this
            </div>
        </div>
        <div className="create_date_copy_4-14">
            <div className="create_date_copy_4-title-8">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="create_date_copy_4-15">
            <div className="create_date_copy_4-15-0">
                <div className="create_date_copy_4-15-0-0">
                    <div className="create_date_copy_4-path-11" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_first_option_to-12">
                The first option to the first question 
            </div>
        </div>
        <div className="create_date_copy_4-16">
            <div className="create_date_copy_4-16-0">
                <div className="create_date_copy_4-16-0-0">
                    <div className="create_date_copy_4-path-39" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_second_option_to-4">
                The second option to the first question
            </div>
        </div>
        <div className="create_date_copy_4-17">
            <div className="create_date_copy_4-17-0">
                <div className="create_date_copy_4-17-0-0">
                    <div className="create_date_copy_4-path-5" /> 
                </div>
            </div>
            <div className="create_date_copy_4-the_third_otion_to_t-12">
                The third otion to the first question is this
            </div>
        </div>
        <div className="create_date_copy_4-18">
            <div className="create_date_copy_4-path-47">
                <div className="create_date_copy_4-18-0-0">
                    <div className="create_date_copy_4-save_and_share_debri-8">
                        Save and Share Debrief 
                    </div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_4-19" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}