// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './createdate.css';

function render() {
    return <div className="createdate-createdate-8">
        <div className="createdate-0">
            <div className="createdate-path-3">
                <div className="createdate-0-0-0">
                    <div className="createdate-0-0-0-0">
                        <div className="createdate-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8443883118787377-1523741622314-0DB0F2C6-E769-4267-88B5-4E0D2EEFD875.png" className="createdate-arrow-left-8" /> 
                        </div>
                    </div>
                    <div className="createdate-title-2">Create a Date</div>
                    <div className="createdate-title_copy-1">Next</div>
                </div>
            </div>
        </div>
        <div className="createdate-1">
            <div className="createdate-title-3">Who</div>
        </div>
        <div className="createdate-2">
            <div className="createdate-path-1">
                <div className="createdate-2-0-0">
                    <div className="createdate-cinderella-1">Cinderella</div>
                </div>
            </div>
        </div>
        <div className="createdate-3">
            <div className="createdate-title-22">Where</div>
        </div>
        <div className="createdate-4">
            <div className="createdate-path-16">
                <div className="createdate-4-0-0">
                    <div className="createdate-narnia_nebraska_ca-3">
                        {"Narnia, Nebraska, CA"}
                    </div>
                </div>
            </div>
        </div>
        <div className="createdate-5">
            <div className="createdate-title-7">When</div>
        </div>
        <div className="createdate-6">
            <div className="createdate-path-12">
                <div className="createdate-6-0-0">
                    <div className="createdate-april_1">
                        {"April 1st, 2018"}
                    </div>
                </div>
            </div>
        </div>
        <div className="createdate-7" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}