// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './create_date_copy_5.css';

function render() {
    return <div className="create_date_copy_5-create_date_copy_5">
        <div className="create_date_copy_5-0">
            <div className="create_date_copy_5-path-1">
                <div className="create_date_copy_5-0-0-0">
                    <div className="create_date_copy_5-0-0-0-0">
                        <div className="create_date_copy_5-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9021685157196913-1523741622115-BB65DD84-57DE-4107-AA2A-350139EAC6DD.png" className="create_date_copy_5-arrow-left-9" /> 
                        </div>
                    </div>
                    <div className="create_date_copy_5-title-9">
                        Private Debrief
                    </div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_5-1">
            <div className="create_date_copy_5-title-1">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="create_date_copy_5-2">
            <div className="create_date_copy_5-2-0">
                <div className="create_date_copy_5-2-0-0">
                    <div className="create_date_copy_5-path-3" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_first_option_to-1">
                The first option to the first question 
            </div>
        </div>
        <div className="create_date_copy_5-3">
            <div className="create_date_copy_5-3-0">
                <div className="create_date_copy_5-3-0-0">
                    <div className="create_date_copy_5-path-8" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_second_option_to-4">
                The second option to the first question
            </div>
        </div>
        <div className="create_date_copy_5-4">
            <div className="create_date_copy_5-4-0">
                <div className="create_date_copy_5-4-0-0">
                    <div className="create_date_copy_5-path-5" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_third_otion_to_t-4">
                The third otion to the first question is this
            </div>
        </div>
        <div className="create_date_copy_5-5">
            <div className="create_date_copy_5-path-17">
                <div className="create_date_copy_5-5-0-0">
                    <div className="create_date_copy_5-anything_you_want_to-1">
                        {"Anything you want to add?"}
                    </div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_5-6">
            <div className="create_date_copy_5-title-10">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="create_date_copy_5-7">
            <div className="create_date_copy_5-7-0">
                <div className="create_date_copy_5-7-0-0">
                    <div className="create_date_copy_5-path-2" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_first_option_to-3">
                The first option to the first question 
            </div>
        </div>
        <div className="create_date_copy_5-8">
            <div className="create_date_copy_5-8-0">
                <div className="create_date_copy_5-8-0-0">
                    <div className="create_date_copy_5-path-16" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_second_option_to-1">
                The second option to the first question
            </div>
        </div>
        <div className="create_date_copy_5-9">
            <div className="create_date_copy_5-9-0">
                <div className="create_date_copy_5-9-0-0">
                    <div className="create_date_copy_5-path-11" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_third_otion_to_t-5">
                The third otion to the first question is this
            </div>
        </div>
        <div className="create_date_copy_5-10">
            <div className="create_date_copy_5-title-7">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="create_date_copy_5-11">
            <div className="create_date_copy_5-11-0">
                <div className="create_date_copy_5-11-0-0">
                    <div className="create_date_copy_5-path-10" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_first_option_to-18">
                The first option to the first question 
            </div>
        </div>
        <div className="create_date_copy_5-12">
            <div className="create_date_copy_5-12-0">
                <div className="create_date_copy_5-12-0-0">
                    <div className="create_date_copy_5-path-14" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_second_option_to-12">
                The second option to the first question
            </div>
        </div>
        <div className="create_date_copy_5-13">
            <div className="create_date_copy_5-13-0">
                <div className="create_date_copy_5-13-0-0">
                    <div className="create_date_copy_5-path-53" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_third_otion_to_t-1">
                The third otion to the first question is this
            </div>
        </div>
        <div className="create_date_copy_5-14">
            <div className="create_date_copy_5-title-15">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="create_date_copy_5-15">
            <div className="create_date_copy_5-15-0">
                <div className="create_date_copy_5-15-0-0">
                    <div className="create_date_copy_5-path-106" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_first_option_to-10">
                The first option to the first question 
            </div>
        </div>
        <div className="create_date_copy_5-16">
            <div className="create_date_copy_5-16-0">
                <div className="create_date_copy_5-16-0-0">
                    <div className="create_date_copy_5-path-165" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_second_option_to-19">
                The second option to the first question
            </div>
        </div>
        <div className="create_date_copy_5-17">
            <div className="create_date_copy_5-17-0">
                <div className="create_date_copy_5-17-0-0">
                    <div className="create_date_copy_5-path-102" /> 
                </div>
            </div>
            <div className="create_date_copy_5-the_third_otion_to_t-13">
                The third otion to the first question is this
            </div>
        </div>
        <div className="create_date_copy_5-18">
            <div className="create_date_copy_5-path-6">
                <div className="create_date_copy_5-18-0-0">
                    <div className="create_date_copy_5-save-2">Save</div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_5-19" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}