// Generated by https://pagedraw.io/pages/9581
import React from 'react';
import './createdate.css';

function render() {
    return <div className="createdate-createdate-6">
        <div className="createdate-0">
            <div className="createdate-path-7">
                <div className="createdate-0-0-0">
                    <div className="createdate-0-0-0-0">
                        <div className="createdate-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1510885143533552-1523736267629-6D8DBA50-F48C-4BE8-A580-9B1E269C31DD.png" className="createdate-arrow-left-1" /> 
                        </div>
                    </div>
                    <div className="createdate-title-3">Create a Date</div>
                </div>
            </div>
        </div>
        <div className="createdate-1">
            <div className="createdate-title-4">With who</div>
        </div>
        <div className="createdate-2">
            <div className="createdate-path-3">
                <div className="createdate-2-0-0">
                    <div className="createdate-cinderella-3">Cinderella</div>
                </div>
            </div>
        </div>
        <div className="createdate-3">
            <div className="createdate-title-6">Where</div>
        </div>
        <div className="createdate-4">
            <div className="createdate-path-1">
                <div className="createdate-4-0-0">
                    <div className="createdate-narnia_nebraska_ca-7">
                        {"Narnia, Nebraska, CA"}
                    </div>
                </div>
            </div>
        </div>
        <div className="createdate-5">
            <div className="createdate-title-1">When</div>
        </div>
        <div className="createdate-6">
            <div className="createdate-path-4">
                <div className="createdate-6-0-0">
                    <div className="createdate-april_1">
                        {"April 1st, 2018"}
                    </div>
                </div>
            </div>
        </div>
        <div className="createdate-7">
            <div className="createdate-title-12">
                {"Don’t forget…"}
            </div>
        </div>
        <div className="createdate-8">
            <div className="createdate-8-0">
                <div className="createdate-8-0-0">
                    <div className="createdate-path-18" /> 
                </div>
            </div>
            <div className="createdate-the_first_thing_that-4">
                {"The first thing that you shouldn’t forget"}
            </div>
        </div>
        <div className="createdate-9">
            <div className="createdate-9-0">
                <div className="createdate-9-0-0">
                    <div className="createdate-path-16" /> 
                </div>
            </div>
            <div className="createdate-the_second_thing_tha-1">
                {"The second thing that you shouldn’t forget"}
            </div>
        </div>
        <div className="createdate-10">
            <div className="createdate-10-0">
                <div className="createdate-10-0-0">
                    <div className="createdate-path-2" /> 
                </div>
            </div>
            <div className="createdate-the_third_thing_that-3">
                {"The third thing that you shouldn’t forget"}
            </div>
        </div>
        <div className="createdate-11">
            <div className="createdate-title-13">
                {"After the Date:"}
            </div>
        </div>
        <div className="createdate-12">
            <div className="createdate-path-22">
                <div className="createdate-12-0-0">
                    <div className="createdate-person-1">
                        Create Private Date Debrief
                    </div>
                </div>
                <div className="createdate-12-0-1">
                    <div className="createdate-info-1">
                        {"Answer some questions to reflect and improve. Only you will be able to see this document"}
                    </div>
                </div>
            </div>
        </div>
        <div className="createdate-13">
            <div className="createdate-path-10">
                <div className="createdate-13-0-0">
                    <div className="createdate-person-4">
                        Create Shared Date Debrief
                    </div>
                </div>
                <div className="createdate-13-0-1">
                    <div className="createdate-info-14">
                        {"Answer some questions to reflect and improve, we will send your partner the same set of questions. The answers to questions you both chose to answer will be visible to both you and your partner"}
                    </div>
                </div>
            </div>
        </div>
        <div className="createdate-14" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}