// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './create_date_copy_6.css';

function render() {
    return <div className="create_date_copy_6-create_date_copy_6">
        <div className="create_date_copy_6-0">
            <div className="create_date_copy_6-path-3">
                <div className="create_date_copy_6-0-0-0">
                    <div className="create_date_copy_6-0-0-0-0">
                        <div className="create_date_copy_6-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1098355597667532-1523741622319-443D471B-AAA4-4D5E-80C4-8707B35A7330.png" className="create_date_copy_6-arrow-left-1" /> 
                        </div>
                    </div>
                    <div className="create_date_copy_6-title-1">
                        Share Debrief
                    </div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_6-1">
            <div className="create_date_copy_6-title-7">
                {"Partner’s Text Number"}
            </div>
        </div>
        <div className="create_date_copy_6-2">
            <div className="create_date_copy_6-path-1">
                <div className="create_date_copy_6-2-0-0">
                    <div className="create_date_copy_6-6">646-220-1598</div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_6-3">
            <div className="create_date_copy_6-path-12">
                <div className="create_date_copy_6-3-0-0">
                    <div className="create_date_copy_6-share_debrief-7">
                        Share Debrief 
                    </div>
                </div>
            </div>
        </div>
        <div className="create_date_copy_6-4" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}