// Generated by https://pagedraw.io/pages/9582
import Datelistitem from './datelistitem';
import React from 'react';
import './datelist.css';

function render() {
    return <div className="datelist-datelist-1">
        <div className="datelist-0">
            <div className="datelist-path-1">
                <div className="datelist-0-0-0">
                    <div className="datelist-icon_menu-3" /> 
                    <div className="datelist-0-0-0-1">
                        <div className="datelist-0-0-0-1-0">
                            <div className="datelist-icon_add-1" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-1">
            <div className="datelist-_2">{ this.props.year }</div>
        </div>
        <div className="datelist-2">
            <div className="datelist-my_dates-1">My Dates</div>
        </div>
        <div className="datelist-3">
            <div className="datelist-datelistitem_instance-1">
                <Datelistitem date={{"name": "Yuriy Dybskiy", "location": "YC Hackathon", "month": "April", "day": "14"}} /> 
            </div>
        </div>
        <div className="datelist-4" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}