// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './dateview.css';

function render() {
    return <div className="dateview-dateview-1">
        <div className="dateview-0">
            <div className="dateview-path-5">
                <div className="dateview-0-0-0">
                    <div className="dateview-path-1">
                        <div className="dateview-0-0-0-0-0">
                            <div className="dateview-0-0-0-0-0-0">
                                <div className="dateview-0-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1182465221061587-1523741622541-37EF50A9-5A5F-420E-86DE-DC4B7E3ADB93.png" className="dateview-arrow-left-1" /> 
                                </div>
                            </div>
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6165291462527206-1523741622543-5456782A-11DA-46CE-AAEB-70C7DA6ADF57.png" className="dateview-action_icons-6" /> 
                        </div>
                    </div>
                </div>
                <div className="dateview-0-0-1">
                    <div className="dateview-julian_leeroy-1">
                        Julian Leeroy
                    </div>
                </div>
                <div className="dateview-0-0-2">
                    <div className="dateview-hint_text-6">
                        <div>{"South of Market, San Fransisco "}</div>
                        <div>{"July 9th, 2018                     "}</div>
                    </div>
                </div>
            </div>
        </div>
        <div className="dateview-1">
            <div className="dateview-title-1">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="dateview-2">
            <div className="dateview-2-0">
                <div className="dateview-2-0-0">
                    <div className="dateview-path-9" /> 
                </div>
            </div>
            <div className="dateview-the_first_option_to-6">
                The first option to the first question 
            </div>
        </div>
        <div className="dateview-3">
            <div className="dateview-3-0">
                <div className="dateview-3-0-0">
                    <div className="dateview-path-15" /> 
                </div>
            </div>
            <div className="dateview-the_second_option_to-1">
                The second option to the first question
            </div>
        </div>
        <div className="dateview-4">
            <div className="dateview-4-0">
                <div className="dateview-4-0-0">
                    <div className="dateview-path-11" /> 
                </div>
            </div>
            <div className="dateview-the_third_otion_to_t-1">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateview-5">
            <div className="dateview-path-8">
                <div className="dateview-5-0-0">
                    <div className="dateview-anything_you_want_to-3">
                        {"Anything you want to add?"}
                    </div>
                </div>
            </div>
        </div>
        <div className="dateview-6">
            <div className="dateview-title-17">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="dateview-7">
            <div className="dateview-7-0">
                <div className="dateview-7-0-0">
                    <div className="dateview-path-94" /> 
                </div>
            </div>
            <div className="dateview-the_first_option_to-1">
                The first option to the first question 
            </div>
        </div>
        <div className="dateview-8">
            <div className="dateview-8-0">
                <div className="dateview-8-0-0">
                    <div className="dateview-path-85" /> 
                </div>
            </div>
            <div className="dateview-the_second_option_to-4">
                The second option to the first question
            </div>
        </div>
        <div className="dateview-9">
            <div className="dateview-9-0">
                <div className="dateview-9-0-0">
                    <div className="dateview-path-16" /> 
                </div>
            </div>
            <div className="dateview-the_third_otion_to_t-10">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateview-10">
            <div className="dateview-title-12">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="dateview-11">
            <div className="dateview-11-0">
                <div className="dateview-11-0-0">
                    <div className="dateview-path-2" /> 
                </div>
            </div>
            <div className="dateview-the_first_option_to-16">
                The first option to the first question 
            </div>
        </div>
        <div className="dateview-12">
            <div className="dateview-12-0">
                <div className="dateview-12-0-0">
                    <div className="dateview-path-12" /> 
                </div>
            </div>
            <div className="dateview-the_second_option_to-9">
                The second option to the first question
            </div>
        </div>
        <div className="dateview-13">
            <div className="dateview-13-0">
                <div className="dateview-13-0-0">
                    <div className="dateview-path-10" /> 
                </div>
            </div>
            <div className="dateview-the_third_otion_to_t-14">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateview-14">
            <div className="dateview-title-10">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="dateview-15">
            <div className="dateview-15-0">
                <div className="dateview-15-0-0">
                    <div className="dateview-path-18" /> 
                </div>
            </div>
            <div className="dateview-the_first_option_to-11">
                The first option to the first question 
            </div>
        </div>
        <div className="dateview-16">
            <div className="dateview-16-0">
                <div className="dateview-16-0-0">
                    <div className="dateview-path-160" /> 
                </div>
            </div>
            <div className="dateview-the_second_option_to-7">
                The second option to the first question
            </div>
        </div>
        <div className="dateview-17">
            <div className="dateview-17-0">
                <div className="dateview-17-0-0">
                    <div className="dateview-path-4" /> 
                </div>
            </div>
            <div className="dateview-the_third_otion_to_t-16">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateview-18" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}