// Generated by https://pagedraw.io/pages/9581
import React from 'react';
import './datelist.css';

function render() {
    return <div className="datelist-datelist-1">
        <div className="datelist-0">
            <div className="datelist-path-1">
                <div className="datelist-0-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8863134696028989-1523736267621-6D3C7261-B0E1-4D58-B95B-5850F98BD169.png" className="datelist-icon_menu-8" /> 
                    <div className="datelist-0-0-0-1">
                        <div className="datelist-0-0-0-1-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1532618885077022-1523736267624-2BB77DB6-FB9D-4CC5-B84E-F3AAA1A969B7.png" className="datelist-icon_add-1" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-1">
            <div className="datelist-_2">{"<  2018   >"}</div>
        </div>
        <div className="datelist-2">
            <div className="datelist-my_dates-1">My Dates</div>
        </div>
        <div className="datelist-3">
            <div className="datelist-path-8">
                <div className="datelist-3-0-0">
                    <div className="datelist-3-0-0-0">
                        <div className="datelist-3-0-0-0-0">
                            <div className="datelist-person-1">Julian Friedman</div>
                        </div>
                        <div className="datelist-3-0-0-0-1">
                            <div className="datelist-info-1">
                                <div>South of Market</div>
                                <br/>
                                <div>Partner Response Received</div>
                            </div>
                        </div>
                    </div>
                    <div className="datelist-3-0-0-1">
                        <div className="datelist-3-0-0-1-0">
                            <div className="datelist-3-0-0-1-0-0">
                                <div className="datelist-rectangle_2">
                                    <div className="datelist-3-0-0-1-0-0-0-0">
                                        <div className="datelist-time-1">Sep</div>
                                    </div>
                                    <div className="datelist-3-0-0-1-0-0-0-1">
                                        <div className="datelist-category_name-8">29th</div>
                                    </div>
                                </div>
                                <div className="datelist-rectangle_3" /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-4">
            <div className="datelist-path-15">
                <div className="datelist-4-0-0">
                    <div className="datelist-4-0-0-0">
                        <div className="datelist-4-0-0-0-0">
                            <div className="datelist-person-15">Julian Friedman</div>
                        </div>
                        <div className="datelist-4-0-0-0-1">
                            <div className="datelist-info-11">
                                <div>South of Market</div>
                                <br/>
                            </div>
                        </div>
                    </div>
                    <div className="datelist-4-0-0-1">
                        <div className="datelist-4-0-0-1-0">
                            <div className="datelist-4-0-0-1-0-0">
                                <div className="datelist-rectangle_2-8">
                                    <div className="datelist-4-0-0-1-0-0-0-0">
                                        <div className="datelist-time-15">Sep</div>
                                    </div>
                                    <div className="datelist-4-0-0-1-0-0-0-1">
                                        <div className="datelist-category_name-2">29th</div>
                                    </div>
                                </div>
                                <div className="datelist-rectangle_3-2" /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-5">
            <div className="datelist-path-17">
                <div className="datelist-5-0-0">
                    <div className="datelist-5-0-0-0">
                        <div className="datelist-5-0-0-0-0">
                            <div className="datelist-person-16">Anastasia Kennedy</div>
                        </div>
                        <div className="datelist-5-0-0-0-1">
                            <div className="datelist-info-13">
                                <div>South of Market</div>
                                <br/>
                            </div>
                        </div>
                    </div>
                    <div className="datelist-5-0-0-1">
                        <div className="datelist-5-0-0-1-0">
                            <div className="datelist-5-0-0-1-0-0">
                                <div className="datelist-rectangle_2-1">
                                    <div className="datelist-5-0-0-1-0-0-0-0">
                                        <div className="datelist-time-4">Sep</div>
                                    </div>
                                    <div className="datelist-5-0-0-1-0-0-0-1">
                                        <div className="datelist-category_name-1">29th</div>
                                    </div>
                                </div>
                                <div className="datelist-rectangle_3-1" /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-6">
            <div className="datelist-path-16">
                <div className="datelist-6-0-0">
                    <div className="datelist-6-0-0-0">
                        <div className="datelist-6-0-0-0-0">
                            <div className="datelist-person-12">
                                Charolette Lacroix
                            </div>
                        </div>
                        <div className="datelist-6-0-0-0-1">
                            <div className="datelist-info-7">
                                <div>South of Market</div>
                                <br/>
                            </div>
                        </div>
                    </div>
                    <div className="datelist-6-0-0-1">
                        <div className="datelist-6-0-0-1-0">
                            <div className="datelist-6-0-0-1-0-0">
                                <div className="datelist-rectangle_2-9">
                                    <div className="datelist-6-0-0-1-0-0-0-0">
                                        <div className="datelist-time-7">Sep</div>
                                    </div>
                                    <div className="datelist-6-0-0-1-0-0-0-1">
                                        <div className="datelist-category_name-17">29th</div>
                                    </div>
                                </div>
                                <div className="datelist-rectangle_3-5" /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-7">
            <div className="datelist-path-2">
                <div className="datelist-7-0-0">
                    <div className="datelist-7-0-0-0">
                        <div className="datelist-7-0-0-0-0">
                            <div className="datelist-person-11">Julian Friedman</div>
                        </div>
                        <div className="datelist-7-0-0-0-1">
                            <div className="datelist-info-73">
                                <div>South of Market</div>
                                <br/>
                                <div>Partner Response Received</div>
                            </div>
                        </div>
                    </div>
                    <div className="datelist-7-0-0-1">
                        <div className="datelist-7-0-0-1-0">
                            <div className="datelist-7-0-0-1-0-0">
                                <div className="datelist-rectangle_2-16">
                                    <div className="datelist-7-0-0-1-0-0-0-0">
                                        <div className="datelist-time-5">Sep</div>
                                    </div>
                                    <div className="datelist-7-0-0-1-0-0-0-1">
                                        <div className="datelist-category_name-12">29th</div>
                                    </div>
                                </div>
                                <div className="datelist-rectangle_3-6" /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-8" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}