// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './datelistitem.css';

function render() {
    return <div className="datelistitem-datelistitem-7">
        <div className="datelistitem-0">
            <div className="datelistitem-path-16">
                <div className="datelistitem-0-0-0">
                    <div className="datelistitem-rectangle_2-7">
                        <div className="datelistitem-0-0-0-0-0">
                            <div className="datelistitem-0-0-0-0-0-0">
                                <div className="datelistitem-0-0-0-0-0-0-0">
                                    <div className="datelistitem-name-6">
                                        { this.props.date.name }
                                    </div>
                                </div>
                                <div className="datelistitem-0-0-0-0-0-0-1">
                                    <div className="datelistitem-location-1">
                                        { this.props.date.location }
                                    </div>
                                </div>
                            </div>
                            <div className="datelistitem-rectangle_2">
                                <div className="datelistitem-0-0-0-0-0-1-0">
                                    <div className="datelistitem-month-1">
                                        { this.props.date.month }
                                    </div>
                                </div>
                                <div className="datelistitem-0-0-0-0-0-1-1">
                                    <div className="datelistitem-date-9">
                                        { this.props.date.day }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="datelistitem-0-0-1">
                    <div className="datelistitem-0-0-1-0">
                        <div className="datelistitem-0-0-1-0-0">
                            <div className="datelistitem-path-9" /> 
                        </div>
                    </div>
                    <a href="{@props.privateLink}" className="datelistitem-0-0-1-1">
                        <div className="datelistitem-label-7">
                            Private check-in
                        </div>
                    </a>
                </div>
                <div className="datelistitem-0-0-2">
                    <div className="datelistitem-0-0-2-0">
                        <div className="datelistitem-0-0-2-0-0">
                            <div className="datelistitem-path-1" /> 
                        </div>
                    </div>
                    <a href="#{@props.sharedLink}" className="datelistitem-0-0-2-1">
                        <div className="datelistitem-label-8">
                            <div>Mutual feedback</div>
                            <div>Not started</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}