// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './dateviewyellow.css';

function render() {
    return <div className="dateviewyellow-dateviewyellow-8">
        <div className="dateviewyellow-0">
            <div className="dateviewyellow-path-6">
                <div className="dateviewyellow-0-0-0">
                    <div className="dateviewyellow-path-1">
                        <div className="dateviewyellow-0-0-0-0-0">
                            <div className="dateviewyellow-0-0-0-0-0-0">
                                <div className="dateviewyellow-0-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6036625358993364-1523741622509-03622E0A-C43F-4CAC-A84F-62F5377693CD.png" className="dateviewyellow-arrow-left-6" /> 
                                </div>
                            </div>
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4089505142097086-1523741622511-5D3C63C2-87D4-4D86-B66E-33E1D66B39C5.png" className="dateviewyellow-action_icons-4" /> 
                        </div>
                    </div>
                </div>
                <div className="dateviewyellow-0-0-1">
                    <div className="dateviewyellow-julian_friedman-5">
                        Julian Friedman
                    </div>
                </div>
                <div className="dateviewyellow-0-0-2">
                    <div className="dateviewyellow-hint_text-1">
                        <div>{"South of Market, San Fransisco "}</div>
                        <div>{"July 9th, 2018                     "}</div>
                    </div>
                </div>
            </div>
        </div>
        <div className="dateviewyellow-1">
            <div className="dateviewyellow-title-7">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="dateviewyellow-2">
            <div className="dateviewyellow-2-0">
                <div className="dateviewyellow-2-0-0">
                    <div className="dateviewyellow-path-7" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_first_option_to-2">
                The first option to the first question 
            </div>
        </div>
        <div className="dateviewyellow-3">
            <div className="dateviewyellow-3-0">
                <div className="dateviewyellow-3-0-0">
                    <div className="dateviewyellow-path-3" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_second_option_to-1">
                The second option to the first question
            </div>
        </div>
        <div className="dateviewyellow-4">
            <div className="dateviewyellow-4-0">
                <div className="dateviewyellow-4-0-0">
                    <div className="dateviewyellow-path-13" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_third_otion_to_t-1">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateviewyellow-5">
            <div className="dateviewyellow-path-5">
                <div className="dateviewyellow-5-0-0">
                    <div className="dateviewyellow-anything_you_want_to-1">
                        {"Anything you want to add?"}
                    </div>
                </div>
            </div>
        </div>
        <div className="dateviewyellow-6">
            <div className="dateviewyellow-title-1">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="dateviewyellow-7">
            <div className="dateviewyellow-7-0">
                <div className="dateviewyellow-7-0-0">
                    <div className="dateviewyellow-path-67" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_first_option_to-1">
                The first option to the first question 
            </div>
        </div>
        <div className="dateviewyellow-8">
            <div className="dateviewyellow-8-0">
                <div className="dateviewyellow-8-0-0">
                    <div className="dateviewyellow-path-11" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_second_option_to-9">
                The second option to the first question
            </div>
        </div>
        <div className="dateviewyellow-9">
            <div className="dateviewyellow-9-0">
                <div className="dateviewyellow-9-0-0">
                    <div className="dateviewyellow-path-19" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_third_otion_to_t-16">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateviewyellow-10">
            <div className="dateviewyellow-title-14">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="dateviewyellow-11">
            <div className="dateviewyellow-11-0">
                <div className="dateviewyellow-11-0-0">
                    <div className="dateviewyellow-path-55" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_first_option_to-9">
                The first option to the first question 
            </div>
        </div>
        <div className="dateviewyellow-12">
            <div className="dateviewyellow-12-0">
                <div className="dateviewyellow-12-0-0">
                    <div className="dateviewyellow-path-4" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_second_option_to-94">
                The second option to the first question
            </div>
        </div>
        <div className="dateviewyellow-13">
            <div className="dateviewyellow-13-0">
                <div className="dateviewyellow-13-0-0">
                    <div className="dateviewyellow-path-17" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_third_otion_to_t-11">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateviewyellow-14">
            <div className="dateviewyellow-title-3">
                {"Q1. This is the first one."}
            </div>
        </div>
        <div className="dateviewyellow-15">
            <div className="dateviewyellow-15-0">
                <div className="dateviewyellow-15-0-0">
                    <div className="dateviewyellow-path-16" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_first_option_to-13">
                The first option to the first question 
            </div>
        </div>
        <div className="dateviewyellow-16">
            <div className="dateviewyellow-16-0">
                <div className="dateviewyellow-16-0-0">
                    <div className="dateviewyellow-path-32" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_second_option_to-14">
                The second option to the first question
            </div>
        </div>
        <div className="dateviewyellow-17">
            <div className="dateviewyellow-17-0">
                <div className="dateviewyellow-17-0-0">
                    <div className="dateviewyellow-path-72" /> 
                </div>
            </div>
            <div className="dateviewyellow-the_third_otion_to_t-7">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateviewyellow-18" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}