// Generated by https://pagedraw.io/pages/9582
import React from 'react';
import './datelist.css';

function render() {
    return <div className="datelist-datelist-1">
        <div className="datelist-0">
            <div className="datelist-path-1">
                <div className="datelist-0-0-0">
                    <div className="datelist-icon_menu-3" /> 
                    <div className="datelist-0-0-0-1">
                        <div className="datelist-0-0-0-1-0">
                            <div className="datelist-icon_add-1" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-1">
            <div className="datelist-_2">{"<  2018   >"}</div>
        </div>
        <div className="datelist-2">
            <div className="datelist-my_dates-1">My Dates</div>
        </div>
        <div className="datelist-3">
            <div className="datelist-path-16">
                <div className="datelist-3-0-0">
                    <div className="datelist-rectangle_2-7">
                        <div className="datelist-3-0-0-0-0">
                            <div className="datelist-3-0-0-0-0-0">
                                <div className="datelist-3-0-0-0-0-0-0">
                                    <div className="datelist-name-6">Anastasia Kennedy</div>
                                </div>
                                <div className="datelist-3-0-0-0-0-0-1">
                                    <div className="datelist-location-1">South of Market</div>
                                </div>
                            </div>
                            <div className="datelist-rectangle_2">
                                <div className="datelist-3-0-0-0-0-1-0">
                                    <div className="datelist-month-1">Sep</div>
                                </div>
                                <div className="datelist-3-0-0-0-0-1-1">
                                    <div className="datelist-date-9">29</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="datelist-3-0-1">
                    <div className="datelist-3-0-1-0">
                        <div className="datelist-3-0-1-0-0">
                            <div className="datelist-3-0-1-0-0-0">
                                <div className="datelist-check_box-5">
                                    <input type="checkbox" className="datelist-3-0-1-0-0-0-0-0" /> 
                                </div>
                                <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1665148711074798-1523741622356-BB8FAC3F-BA0F-4364-9DB6-1B338B9622DD.png" className="datelist-glyph-1" /> 
                            </div>
                        </div>
                    </div>
                    <div className="datelist-label-7">Private check-in</div>
                </div>
                <div className="datelist-3-0-2">
                    <div className="datelist-3-0-2-0">
                        <div className="datelist-3-0-2-0-0">
                            <div className="datelist-path-13" /> 
                        </div>
                    </div>
                    <div className="datelist-label-8">
                        <div>Mutual feedback</div>
                        <div>Not started</div>
                    </div>
                </div>
            </div>
        </div>
        <div className="datelist-4" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}