// Generated by https://pagedraw.io/pages/9581
import React from 'react';
import './dateview.css';

function render() {
    return <div className="dateview-dateview-2">
        <div className="dateview-0">
            <div className="dateview-path-18">
                <div className="dateview-0-0-0">
                    <div className="dateview-path-1">
                        <div className="dateview-0-0-0-0-0">
                            <div className="dateview-0-0-0-0-0-0">
                                <div className="dateview-0-0-0-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8930047965862018-1523736267558-75D79913-0D00-494D-BCB9-2BCB3F09AC01.png" className="dateview-arrow-left-8" /> 
                                </div>
                            </div>
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1797535732597142-1523736267560-7D6E42AE-DF39-421E-9617-21073B60BCC3.png" className="dateview-action_icons-1" /> 
                        </div>
                    </div>
                </div>
                <div className="dateview-0-0-1">
                    <div className="dateview-julian_leeroy-6">
                        Julian Leeroy
                    </div>
                </div>
                <div className="dateview-0-0-2">
                    <div className="dateview-hint_text-2">
                        <div>{"South of Market, San Fransisco "}</div>
                        <div>{"July 9th, 2018                     "}</div>
                    </div>
                </div>
            </div>
        </div>
        <div className="dateview-1">
            <div className="dateview-title-1">
                {"Q1. This is the first question."}
            </div>
        </div>
        <div className="dateview-2">
            <div className="dateview-2-0">
                <div className="dateview-2-0-0">
                    <div className="dateview-path-15" /> 
                </div>
            </div>
            <div className="dateview-the_first_option_to-6">
                The first option to the first question 
            </div>
        </div>
        <div className="dateview-3">
            <div className="dateview-3-0">
                <div className="dateview-3-0-0">
                    <div className="dateview-path-12" /> 
                </div>
            </div>
            <div className="dateview-the_second_option_to-5">
                The second option to the first question
            </div>
        </div>
        <div className="dateview-4">
            <div className="dateview-4-0">
                <div className="dateview-4-0-0">
                    <div className="dateview-path-5" /> 
                </div>
            </div>
            <div className="dateview-the_third_otion_to_t-1">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateview-5">
            <div className="dateview-my_own_comments_on_t-1">
                {"My own comments on the date go as like such, this is what I wrote down for question one."}
            </div>
        </div>
        <div className="dateview-6">
            <div className="dateview-title-16">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="dateview-7">
            <div className="dateview-7-0">
                <div className="dateview-7-0-0">
                    <div className="dateview-path-13" /> 
                </div>
            </div>
            <div className="dateview-the_first_option_to-61">
                The first option to the first question 
            </div>
        </div>
        <div className="dateview-8">
            <div className="dateview-8-0">
                <div className="dateview-8-0-0">
                    <div className="dateview-path-181" /> 
                </div>
            </div>
            <div className="dateview-the_second_option_to-1">
                The second option to the first question
            </div>
        </div>
        <div className="dateview-9">
            <div className="dateview-9-0">
                <div className="dateview-9-0-0">
                    <div className="dateview-path-134" /> 
                </div>
            </div>
            <div className="dateview-the_third_otion_to_t-15">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateview-10">
            <div className="dateview-title-2">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="dateview-11">
            <div className="dateview-11-0">
                <div className="dateview-11-0-0">
                    <div className="dateview-path-11" /> 
                </div>
            </div>
            <div className="dateview-the_first_option_to-1">
                The first option to the first question 
            </div>
        </div>
        <div className="dateview-12">
            <div className="dateview-12-0">
                <div className="dateview-12-0-0">
                    <div className="dateview-path-17" /> 
                </div>
            </div>
            <div className="dateview-the_second_option_to-2">
                The second option to the first question
            </div>
        </div>
        <div className="dateview-13">
            <div className="dateview-13-0">
                <div className="dateview-13-0-0">
                    <div className="dateview-path-6" /> 
                </div>
            </div>
            <div className="dateview-the_third_otion_to_t-10">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateview-14">
            <div className="dateview-title-17">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="dateview-15">
            <div className="dateview-15-0">
                <div className="dateview-15-0-0">
                    <div className="dateview-path-138" /> 
                </div>
            </div>
            <div className="dateview-the_first_option_to-11">
                The first option to the first question 
            </div>
        </div>
        <div className="dateview-16">
            <div className="dateview-16-0">
                <div className="dateview-16-0-0">
                    <div className="dateview-path-8" /> 
                </div>
            </div>
            <div className="dateview-the_second_option_to-52">
                The second option to the first question
            </div>
        </div>
        <div className="dateview-17">
            <div className="dateview-17-0">
                <div className="dateview-17-0-0">
                    <div className="dateview-path-119" /> 
                </div>
            </div>
            <div className="dateview-the_third_otion_to_t-17">
                The third otion to the first question is this
            </div>
        </div>
        <div className="dateview-18" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}