// Generated by https://pagedraw.io/pages/9581
import React from 'react';
import './privatedebrief.css';

function render() {
    return <div className="privatedebrief-privatedebrief-9">
        <div className="privatedebrief-0">
            <div className="privatedebrief-path-1">
                <div className="privatedebrief-0-0-0">
                    <div className="privatedebrief-0-0-0-0">
                        <div className="privatedebrief-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9914364930612564-1523736267142-9BEE21B9-0C83-49F6-9189-726E8AEFCE24.png" className="privatedebrief-arrow-left-9" /> 
                        </div>
                    </div>
                    <div className="privatedebrief-title-9">
                        Private Debrief
                    </div>
                </div>
            </div>
        </div>
        <div className="privatedebrief-1">
            <div className="privatedebrief-title-7">
                {"Q1. This is the first question."}
            </div>
        </div>
        <div className="privatedebrief-2">
            <div className="privatedebrief-2-0">
                <div className="privatedebrief-2-0-0">
                    <div className="privatedebrief-path-7" /> 
                </div>
            </div>
            <div className="privatedebrief-the_first_option_to-3">
                The first option to the first question 
            </div>
        </div>
        <div className="privatedebrief-3">
            <div className="privatedebrief-3-0">
                <div className="privatedebrief-3-0-0">
                    <div className="privatedebrief-path-71" /> 
                </div>
            </div>
            <div className="privatedebrief-the_second_option_to-1">
                The second option to the first question
            </div>
        </div>
        <div className="privatedebrief-4">
            <div className="privatedebrief-4-0">
                <div className="privatedebrief-4-0-0">
                    <div className="privatedebrief-path-4" /> 
                </div>
            </div>
            <div className="privatedebrief-the_third_otion_to_t-1">
                The third otion to the first question is this
            </div>
        </div>
        <div className="privatedebrief-5">
            <div className="privatedebrief-path-15">
                <div className="privatedebrief-5-0-0">
                    <div className="privatedebrief-anything_you_want_to-2">
                        {"Anything you want to add?"}
                    </div>
                </div>
            </div>
        </div>
        <div className="privatedebrief-6">
            <div className="privatedebrief-title-91">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="privatedebrief-7">
            <div className="privatedebrief-7-0">
                <div className="privatedebrief-7-0-0">
                    <div className="privatedebrief-path-10" /> 
                </div>
            </div>
            <div className="privatedebrief-the_first_option_to-6">
                The first option to the first question 
            </div>
        </div>
        <div className="privatedebrief-8">
            <div className="privatedebrief-8-0">
                <div className="privatedebrief-8-0-0">
                    <div className="privatedebrief-path-8" /> 
                </div>
            </div>
            <div className="privatedebrief-the_second_option_to-17">
                The second option to the first question
            </div>
        </div>
        <div className="privatedebrief-9">
            <div className="privatedebrief-9-0">
                <div className="privatedebrief-9-0-0">
                    <div className="privatedebrief-path-11" /> 
                </div>
            </div>
            <div className="privatedebrief-the_third_otion_to_t-12">
                The third otion to the first question is this
            </div>
        </div>
        <div className="privatedebrief-10">
            <div className="privatedebrief-title-1">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="privatedebrief-11">
            <div className="privatedebrief-11-0">
                <div className="privatedebrief-11-0-0">
                    <div className="privatedebrief-path-109" /> 
                </div>
            </div>
            <div className="privatedebrief-the_first_option_to-1">
                The first option to the first question 
            </div>
        </div>
        <div className="privatedebrief-12">
            <div className="privatedebrief-12-0">
                <div className="privatedebrief-12-0-0">
                    <div className="privatedebrief-path-78" /> 
                </div>
            </div>
            <div className="privatedebrief-the_second_option_to-174">
                The second option to the first question
            </div>
        </div>
        <div className="privatedebrief-13">
            <div className="privatedebrief-13-0">
                <div className="privatedebrief-13-0-0">
                    <div className="privatedebrief-path-75" /> 
                </div>
            </div>
            <div className="privatedebrief-the_third_otion_to_t-15">
                The third otion to the first question is this
            </div>
        </div>
        <div className="privatedebrief-14">
            <div className="privatedebrief-title-16">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="privatedebrief-15">
            <div className="privatedebrief-15-0">
                <div className="privatedebrief-15-0-0">
                    <div className="privatedebrief-path-6" /> 
                </div>
            </div>
            <div className="privatedebrief-the_first_option_to-7">
                The first option to the first question 
            </div>
        </div>
        <div className="privatedebrief-16">
            <div className="privatedebrief-16-0">
                <div className="privatedebrief-16-0-0">
                    <div className="privatedebrief-path-17" /> 
                </div>
            </div>
            <div className="privatedebrief-the_second_option_to-10">
                The second option to the first question
            </div>
        </div>
        <div className="privatedebrief-17">
            <div className="privatedebrief-17-0">
                <div className="privatedebrief-17-0-0">
                    <div className="privatedebrief-path-101" /> 
                </div>
            </div>
            <div className="privatedebrief-the_third_otion_to_t-7">
                The third otion to the first question is this
            </div>
        </div>
        <div className="privatedebrief-18">
            <div className="privatedebrief-path-14">
                <div className="privatedebrief-18-0-0">
                    <div className="privatedebrief-save-5">Save</div>
                </div>
            </div>
        </div>
        <div className="privatedebrief-19" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}