// Generated by https://pagedraw.io/pages/9581
import React from 'react';
import './shareddebrief.css';

function render() {
    return <div className="shareddebrief-shareddebrief-2">
        <div className="shareddebrief-0">
            <div className="shareddebrief-path-2">
                <div className="shareddebrief-0-0-0">
                    <div className="shareddebrief-0-0-0-0">
                        <div className="shareddebrief-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7294677536885797-1523736267149-047A55C0-3C14-4B3C-AB38-0664ACCC8E92.png" className="shareddebrief-arrow-left-7" /> 
                        </div>
                    </div>
                    <div className="shareddebrief-title-1">Shared Debrief</div>
                </div>
            </div>
        </div>
        <div className="shareddebrief-1">
            <div className="shareddebrief-title-5">
                {"Q1. This is the first question."}
            </div>
        </div>
        <div className="shareddebrief-2">
            <div className="shareddebrief-2-0">
                <div className="shareddebrief-2-0-0">
                    <div className="shareddebrief-path-4" /> 
                </div>
            </div>
            <div className="shareddebrief-the_first_option_to-1">
                The first option to the first question 
            </div>
        </div>
        <div className="shareddebrief-3">
            <div className="shareddebrief-3-0">
                <div className="shareddebrief-3-0-0">
                    <div className="shareddebrief-path-8" /> 
                </div>
            </div>
            <div className="shareddebrief-the_second_option_to-1">
                The second option to the first question
            </div>
        </div>
        <div className="shareddebrief-4">
            <div className="shareddebrief-4-0">
                <div className="shareddebrief-4-0-0">
                    <div className="shareddebrief-path-1" /> 
                </div>
            </div>
            <div className="shareddebrief-the_third_otion_to_t-1">
                The third otion to the first question is this
            </div>
        </div>
        <div className="shareddebrief-5">
            <div className="shareddebrief-path-13">
                <div className="shareddebrief-5-0-0">
                    <div className="shareddebrief-anything_you_want_to-7">
                        {"Anything you want to add?"}
                    </div>
                </div>
            </div>
        </div>
        <div className="shareddebrief-6">
            <div className="shareddebrief-title-2">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="shareddebrief-7">
            <div className="shareddebrief-7-0">
                <div className="shareddebrief-7-0-0">
                    <div className="shareddebrief-path-11" /> 
                </div>
            </div>
            <div className="shareddebrief-the_first_option_to-12">
                The first option to the first question 
            </div>
        </div>
        <div className="shareddebrief-8">
            <div className="shareddebrief-8-0">
                <div className="shareddebrief-8-0-0">
                    <div className="shareddebrief-path-133" /> 
                </div>
            </div>
            <div className="shareddebrief-the_second_option_to-2">
                The second option to the first question
            </div>
        </div>
        <div className="shareddebrief-9">
            <div className="shareddebrief-9-0">
                <div className="shareddebrief-9-0-0">
                    <div className="shareddebrief-path-3" /> 
                </div>
            </div>
            <div className="shareddebrief-the_third_otion_to_t-5">
                The third otion to the first question is this
            </div>
        </div>
        <div className="shareddebrief-10">
            <div className="shareddebrief-title-17">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="shareddebrief-11">
            <div className="shareddebrief-11-0">
                <div className="shareddebrief-11-0-0">
                    <div className="shareddebrief-path-113" /> 
                </div>
            </div>
            <div className="shareddebrief-the_first_option_to-2">
                The first option to the first question 
            </div>
        </div>
        <div className="shareddebrief-12">
            <div className="shareddebrief-12-0">
                <div className="shareddebrief-12-0-0">
                    <div className="shareddebrief-path-7" /> 
                </div>
            </div>
            <div className="shareddebrief-the_second_option_to-8">
                The second option to the first question
            </div>
        </div>
        <div className="shareddebrief-13">
            <div className="shareddebrief-13-0">
                <div className="shareddebrief-13-0-0">
                    <div className="shareddebrief-path-39" /> 
                </div>
            </div>
            <div className="shareddebrief-the_third_otion_to_t-3">
                The third otion to the first question is this
            </div>
        </div>
        <div className="shareddebrief-14">
            <div className="shareddebrief-title-11">
                {"Q2. This is the second question."}
            </div>
        </div>
        <div className="shareddebrief-15">
            <div className="shareddebrief-15-0">
                <div className="shareddebrief-15-0-0">
                    <div className="shareddebrief-path-84" /> 
                </div>
            </div>
            <div className="shareddebrief-the_first_option_to-9">
                The first option to the first question 
            </div>
        </div>
        <div className="shareddebrief-16">
            <div className="shareddebrief-16-0">
                <div className="shareddebrief-16-0-0">
                    <div className="shareddebrief-path-74" /> 
                </div>
            </div>
            <div className="shareddebrief-the_second_option_to-4">
                The second option to the first question
            </div>
        </div>
        <div className="shareddebrief-17">
            <div className="shareddebrief-17-0">
                <div className="shareddebrief-17-0-0">
                    <div className="shareddebrief-path-9" /> 
                </div>
            </div>
            <div className="shareddebrief-the_third_otion_to_t-10">
                The third otion to the first question is this
            </div>
        </div>
        <div className="shareddebrief-18">
            <div className="shareddebrief-path-15">
                <div className="shareddebrief-18-0-0">
                    <div className="shareddebrief-save_and_share_debri-3">
                        Save and Share Debrief 
                    </div>
                </div>
            </div>
        </div>
        <div className="shareddebrief-19" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}