// Generated by https://pagedraw.io/pages/9581
import React from 'react';
import './shared_debrief_phone.css';

function render() {
    return <div className="shared_debrief_phone-shared_debrief_phone-4">
        <div className="shared_debrief_phone-0">
            <div className="shared_debrief_phone-path-6">
                <div className="shared_debrief_phone-0-0-0">
                    <div className="shared_debrief_phone-0-0-0-0">
                        <div className="shared_debrief_phone-0-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1150335963271659-1523736267406-FB3A85A4-34F0-433A-98FE-04AE861E7202.png" className="shared_debrief_phone-arrow-left-1" /> 
                        </div>
                    </div>
                    <div className="shared_debrief_phone-title-1">
                        Share Debrief
                    </div>
                </div>
            </div>
        </div>
        <div className="shared_debrief_phone-1">
            <div className="shared_debrief_phone-title-10">
                {"Partner’s Text Number"}
            </div>
        </div>
        <div className="shared_debrief_phone-2">
            <div className="shared_debrief_phone-path-1">
                <div className="shared_debrief_phone-2-0-0">
                    <div className="shared_debrief_phone-6">646-220-1598</div>
                </div>
            </div>
        </div>
        <div className="shared_debrief_phone-3">
            <div className="shared_debrief_phone-path-13">
                <div className="shared_debrief_phone-3-0-0">
                    <div className="shared_debrief_phone-share_debrief-1">
                        Share Debrief 
                    </div>
                </div>
            </div>
        </div>
        <div className="shared_debrief_phone-4" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}